include: package:lint/analysis_options_package.yaml

linter:
  rules:
    prefer_relative_imports: true
    always_specify_types: true
    avoid_redundant_argument_values: false
    missing_whitespace_between_adjacent_strings: false
#     avoid_print: false
#     overridden_fields: false
#     prefer_initializing_formals: false
#     avoid_escaping_inner_quotes: false
#     avoid_classes_with_only_static_members: false


analyzer:
  strong-mode:
    implicit-casts: true
  errors:
    missing_required_param: error
